name: Daily render
on:
  schedule:
    - cron: '0 17 * * *' # Runs daily at 8:00 UTC

jobs:
  curl-website:
    runs-on: ubuntu-latest
    steps:
      - name: Run CURL on Website
        run: curl https://digital-services-5q9t.onrender.com
